server:
  port: 8081
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost/bdSpringSI61
    username: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: create
    show-sql: false
